var DB5 = {
    "users": [
        {
            "user_id": "1",
            "credentials": "0",
            "password": "p",
            "username": "u",
            "first_name": "Admin",
            "last_name": "Root",
            "email": "Admin.Root@it.uu.se",
            "phone": "911",
            "capital": 2000,
        },
        {
            "user_id": "2",
            "credentials": "0",
            "password": "b690bc2447d40ea8a6f78345eb979a28",
            "username": "jorass",
            "first_name": "Jory",
            "last_name": "Assies",
            "email": "jory.assies@it.uu.se",
            "phone": "0704811411",
            "capital": 2000,
        },
        {
            "user_id": "28",
            "credentials": "3",
            "password": "b612f428e4a53386fdb98f6c2164c16c",
            "username": "sulstr",
            "first_name": "Sulayman",
            "last_name": "Street",
            "email": "sulayman.street@it.uu.se",
            "phone": "0701517627",
            "capital": 2000,
        },
        {
            "user_id": "27",
            "credentials": "3",
            "password": "c0d9251f9af5e7410c6a3932f696c449",
            "username": "orapan",
            "first_name": "Orabela",
            "last_name": "Panders",
            "email": "orabela.panders@it.uu.se",
            "phone": "0701503294",
            "capital": 2000,
        },
        {
            "user_id": "26",
            "credentials": "3",
            "password": "4ec434994decffa3005b477cc7f992e6",
            "username": "kenolg",
            "first_name": "Kenan",
            "last_name": "Olguin",
            "email": "kenan.olguin@it.uu.se",
            "phone": "0706569560",
            "capital": 2000,
        },
        {
            "user_id": "25",
            "credentials": "0",
            "password": "971299fa95fe467db26e8bf01864d48d",
            "username": "saskru",
            "first_name": "Sa\u0161a",
            "last_name": "Kr\u00fcger",
            "email": "sasa.kruger@it.uu.se",
            "phone": "0705349276",
            "capital": 2000,
        },
        {
            "user_id": "24",
            "credentials": "0",
            "password": "2a3db2cc165057da53ef13a348e9787f",
            "username": "ervtod",
            "first_name": "Ervin",
            "last_name": "Todd",
            "email": "ervin.todd@it.uu.se",
            "phone": "0702339018",
            "capital": 2000,
        }]
};
